let dict = {
    "United States of America": "Estados Unidos de América",
    "Spain": "España",
    "Italy": "Italia",
    "United Kingdom": "Reino Unido",
    "Russian Federation": "Federación Rusa",
    "France": "Francia",
    "Germany": "Alemania",
    "Brazil": "Brasil",
    "Turkey": "Turquía",
    "Iran, Islamic Republic of": "República Islámica de Irán",
    "Canada": "Canadá",
    "Peru": "Perú",
    "India": "India",
    "Belgium": "Bélgica",
    "Netherlands": "Países Bajos",
    "Saudi Arabia": "Arabia Saudita",
    "Mexico": "México",
    "Switzerland": "Suiza",
    "Ecuador": "Ecuador",
    "Portugal": "Portugal",
    "Pakistan": "Pakistán",
    "Chile": "Chile",
    "Sweden": "Suecia",
    "Ireland": "Irlanda",
    "Singapore": "Singapur",
    "Belarus": "Bielorrusia",
    "Qatar": "Katar",
    "United Arab Emirates": "Emiratos Árabes Unidos",
    "Israel": "Israel",
    "Austria": "Austria",
    "Japan": "Japón",
    "Poland": "Polonia",
    "Romania": "Rumania",
    "Ukraine": "Ucrania",
    "Bangladesh": "Bangladesh",
    "Indonesia": "Indonesia",
    "Korea (South)": "Corea del Sur)",
    "Philippines": "Filipinas",
    "Denmark": "Dinamarca",
    "Colombia": "Colombia",
    "Serbia": "Serbia",
    "Dominican Republic": "República Dominicana",
    "South Africa": "Sudáfrica",
    "Egypt": "Egipto",
    "Czech Republic": "Republica Checa",
    "Norway": "Noruega",
    "Panama": "Panamá",
    "Kuwait": "Kuwait",
    "Malaysia": "Malasia",
    "Finland": "Finlandia",
    "Morocco": "Marruecos",
    "Argentina": "Argentina",
    "Algeria": "Argelia",
    "Kazakhstan": "Kazajstán",
    "Moldova": "Moldavia",
    "Bahrain": "Bahrein",
    "Ghana": "Ghana",
    "Nigeria": "Nigeria",
    "Luxembourg": "Luxemburgo",
    "Afghanistan": "Afganistán",
    "Hungary": "Hungría",
    "Oman": "Omán",
    "Armenia": "Armenia",
    "Thailand": "Tailandia",
    "Greece": "Grecia",
    "Iraq": "Irak",
    "Uzbekistan": "Uzbekistán",
    "Azerbaijan": "Azerbaiyán",
    "Cameroon": "Camerún",
    "Bolivia": "Bolivia",
    "Croatia": "Croacia",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    "Guinea": "Guinea",
    "Bulgaria": "Bulgaria",
    "Iceland": "Islandia",
    "Honduras": "Honduras",
    "Cuba": "Cuba",
    "Estonia": "Estonia",
    "Côte d'Ivoire": "Costa de Marfil",
    "Macedonia, Republic of": "Macedonia, República de",
    "Senegal": "Senegal",
    "New Zealand": "Nueva Zelanda",
    "Slovakia": "Eslovaquia",
    "Slovenia": "Eslovenia",
    "Lithuania": "Lituania",
    "Djibouti": "Djibouti",
    "Sudan": "Sudán",
    "Tunisia": "Túnez",
    "Congo (Kinshasa)": "Congo (Kinshasa)",
    "Latvia": "Letonia",
    "Somalia": "Somalia",
    "Kyrgyzstan": "Kirguistán",
    "Guatemala": "Guatemala",
    "Cyprus": "Chipre",
    "Republic of Kosovo": "Republica de Kosovo",
    "Albania": "Albania",
    "Sri Lanka": "Sri Lanka",
    "Lebanon": "Líbano",
    "Niger": "Níger",
    "Costa Rica": "Costa Rica",
    "Andorra": "Andorra",
    "Burkina Faso": "Burkina Faso",
    "Maldives": "Maldivas",
    "El Salvador": "El Salvador",
    "Uruguay": "Uruguay",
    "Mali": "Mali",
    "Georgia": "Georgia",
    "San Marino": "San Marino",
    "Kenya": "Kenia",
    "Gabon": "Gabón",
    "Guinea-Bissau": "Guinea-Bissau",
    "Paraguay": "Paraguay",
    "Tajikistan": "Tayikistán",
    "Tanzania, United Republic of": "Tanzania, República Unida de",
    "Jordan": "Jordán",
    "Jamaica": "Jamaica",
    "Malta": "Malta",
    "Taiwan, Republic of China": "Taiwán, República de China",
    "Equatorial Guinea": "Guinea Ecuatorial",
    "Venezuela (Bolivarian Republic)": "Venezuela (república bolivariana)",
    "Palestinian Territory": "Territorio Palestino",
    "Mauritius": "Mauricio",
    "Montenegro": "Montenegro",
    "Viet Nam": "Viet Nam",
    "Congo (Brazzaville)": "Congo (Brazzaville)",
    "Rwanda": "Ruanda",
    "Chad": "Chad",
    "Sierra Leone": "Sierra Leona",
    "Benin": "Benin",
    "Cape Verde": "Cabo Verde",
    "Sao Tome and Principe": "Santo Tomé y Príncipe",
    "Liberia": "Liberia",
    "Ethiopia": "Etiopía",
    "Madagascar": "Madagascar",
    "Myanmar": "Myanmar",
    "Zambia": "Zambia",
    "Swaziland": "Swazilandia",
    "Haiti": "Haití",
    "Togo": "Ir",
    "Central African Republic": "República Centroafricana",
    "Brunei Darussalam": "Brunei Darussalam",
    "Cambodia": "Camboya",
    "South Sudan": "Sudán del Sur",
    "Trinidad and Tobago": "Trinidad y Tobago",
    "Nepal": "Nepal",
    "Uganda": "Uganda",
    "Monaco": "Mónaco",
    "Guyana": "Guayana",
    "Bahamas": "Bahamas",
    "Barbados": "Barbados",
    "Liechtenstein": "Liechtenstein",
    "Mozambique": "Mozambique",
    "Libya": "Libia",
    "Syrian Arab Republic (Syria)": "República Árabe Siria (Siria)",
    "Angola": "Angola",
    "Malawi": "Malawi",
    "Mongolia": "Mongolia",
    "Eritrea": "Eritrea",
    "Yemen": "Yemen",
    "Zimbabwe": "Zimbabue",
    "Antigua and Barbuda": "Antigua y Barbuda",
    "Timor-Leste": "Timor-Leste",
    "Botswana": "Botsuana",
    "Grenada": "Granada",
    "Gambia": "Gambia",
    "Lao PDR": "República Democrática Popular Lao",
    "Belize": "Belice",
    "Fiji": "Fiyi",
    "Saint Lucia": "Santa Lucía",
    "Saint Vincent and Grenadines": "San Vicente y Granadinas",
    "Dominica": "Dominica",
    "Namibia": "Namibia",
    "Nicaragua": "Nicaragua",
    "Burundi": "Burundi",
    "Saint Kitts and Nevis": "San Cristóbal y Nieves",
    "Holy See (Vatican City State)": "Santa Sede (Estado de la Ciudad del Vaticano)",
    "Seychelles": "Seychelles",
    "Suriname": "Surinam",
    "Comoros": "Comoras",
    "Mauritania": "Mauritania",
    "Papua New Guinea": "Papúa Nueva Guinea",
    "Bhutan": "Bután",
    "Western Sahara": "Sahara Occidental",
    "ALA Aland Islands": "ALA Aland Islands",
    "American Samoa": "Samoa Americana",
    "Anguilla": "Anguila",
    "Antarctica": "Antártida",
    "Aruba": "Aruba",
    "Australia": "Australia",
    "Bermuda": "islas Bermudas",
    "Bouvet Island": "Isla Bouvet",
    "British Indian Ocean Territory": "Territorio Británico del Océano Índico",
    "British Virgin Islands": "Islas Vírgenes Británicas",
    "Cayman Islands": "Islas Caimán",
    "China": "China",
    "Christmas Island": "Isla de Navidad",
    "Cocos (Keeling) Islands": "Islas Cocos (Keeling)",
    "Cook Islands": "Islas Cook",
    "Falkland Islands (Malvinas)": "Islas Malvinas (Falkland Islands)",
    "Faroe Islands": "Islas Faroe",
    "French Guiana": "Guayana Francesa",
    "French Polynesia": "Polinesia francés",
    "French Southern Territories": "Territorios Franceses del Sur",
    "Gibraltar": "Gibraltar",
    "Greenland": "Groenlandia",
    "Guadeloupe": "Guadalupe",
    "Guam": "Guam",
    "Guernsey": "Guernsey",
    "Heard and Mcdonald Islands": "Islas Heard y Mcdonald",
    "Hong Kong, SAR China": "Hong Kong, SAR China",
    "Isle of Man": "Isla del hombre",
    "Jersey": "Jersey",
    "Kiribati": "Kiribati",
    "Korea (North)": "Corea del Norte",
    "Lesotho": "Lesoto",
    "Macao, SAR China": "Macao, SAR China",
    "Marshall Islands": "Islas Marshall",
    "Martinique": "Martinica",
    "Mayotte": "Mayotte",
    "Micronesia, Federated States of": "Micronesia, Estados Federados de",
    "Montserrat": "Montserrat",
    "Nauru": "Nauru",
    "Netherlands Antilles": "Antillas Holandesas",
    "New Caledonia": "Nueva Caledonia",
    "Niue": "Niue",
    "Norfolk Island": "Isla Norfolk",
    "Northern Mariana Islands": "Islas Marianas del Norte",
    "Palau": "Palau",
    "Pitcairn": "Pitcairn",
    "Puerto Rico": "Puerto Rico",
    "Réunion": "Reunión",
    "Saint Helena": "Santa helena",
    "Saint Pierre and Miquelon": "San Pedro y Miquelón",
    "Saint-Barthélemy": "San Bartolomé",
    "Saint-Martin (French part)": "Saint-Martin (parte francesa)",
    "Samoa": "Samoa",
    "Solomon Islands": "Islas Salomón",
    "South Georgia and the South Sandwich Islands": "Georgia del sur y las islas Sandwich del sur",
    "Svalbard and Jan Mayen Islands": "Islas Svalbard y Jan Mayen",
    "Tokelau": "Tokelau",
    "Tonga": "Tonga",
    "Turkmenistan": "Turkmenistán",
    "Turks and Caicos Islands": "Islas Turcas y Caicos",
    "Tuvalu": "Tuvalu",
    "US Minor Outlying Islands": "Islas ultramarinas menores de EE. UU.",
    "Vanuatu": "Vanuatu",
    "Virgin Islands, US": "Islas Vírgenes, EE. UU.",
    "Wallis and Futuna Islands": "Islas Wallis y Futuna"
}